name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create APK Archive
        run: |
          mkdir -p output_apk
          zip -r output_apk/PhoneChecker.zip index.html css js

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: PhoneChecker-Package
          path: output_apk/
